import type { Ingredient } from "./types";

/**
 * Prices are mid-range Canadian supermarket estimates in CAD (Loblaws /
 * Superstore ballpark, not Costco bulk and not a downtown corner store).
 * They drive the cost breakdown, so edit them here when your receipts disagree
 * and every week recalculates.
 */
export const INGREDIENTS: Ingredient[] = [
  // ---------- Meat ----------
  {
    id: "chicken-breast",
    name: "Chicken breast",
    aisle: "meat",
    unit: "g",
    kcalPer100: 165,
    proteinPer100: 31,
    packSize: 1000,
    packPrice: 14.0,
    packLabel: "1 kg tray",
  },
  {
    id: "chicken-thigh",
    name: "Chicken thighs, boneless",
    aisle: "meat",
    unit: "g",
    kcalPer100: 209,
    proteinPer100: 26,
    packSize: 1000,
    packPrice: 11.5,
    packLabel: "1 kg tray",
  },
  {
    id: "ground-beef",
    name: "Lean ground beef",
    aisle: "meat",
    unit: "g",
    kcalPer100: 250,
    proteinPer100: 26,
    packSize: 500,
    packPrice: 7.5,
    packLabel: "500 g pack",
  },
  {
    id: "ground-turkey",
    name: "Ground turkey",
    aisle: "meat",
    unit: "g",
    kcalPer100: 170,
    proteinPer100: 27,
    packSize: 500,
    packPrice: 6.5,
    packLabel: "500 g pack",
  },
  {
    id: "pork-loin",
    name: "Pork loin chops",
    aisle: "meat",
    unit: "g",
    kcalPer100: 242,
    proteinPer100: 27,
    packSize: 800,
    packPrice: 9.0,
    packLabel: "800 g pack",
  },

  // ---------- Seafood ----------
  {
    id: "salmon",
    name: "Salmon fillets",
    aisle: "seafood",
    unit: "g",
    kcalPer100: 208,
    proteinPer100: 20,
    packSize: 600,
    packPrice: 17.0,
    packLabel: "600 g (4 fillets)",
  },
  {
    id: "tuna-can",
    name: "Canned tuna",
    aisle: "pantry",
    unit: "g",
    kcalPer100: 116,
    proteinPer100: 26,
    packSize: 170,
    packPrice: 2.1,
    packLabel: "170 g tin",
    eachGrams: 170,
    eachLabel: "tin",
  },

  // ---------- Dairy & eggs ----------
  {
    id: "eggs",
    name: "Eggs, large",
    aisle: "dairy",
    unit: "g",
    kcalPer100: 143,
    proteinPer100: 12.6,
    packSize: 600,
    packPrice: 4.8,
    packLabel: "dozen",
    eachGrams: 50,
    eachLabel: "egg",
  },
  {
    id: "greek-yogurt",
    name: "Greek yogurt, 2%",
    aisle: "dairy",
    unit: "g",
    kcalPer100: 73,
    proteinPer100: 10,
    packSize: 750,
    packPrice: 6.5,
    packLabel: "750 g tub",
  },
  {
    id: "cheddar",
    name: "Cheddar, shredded",
    aisle: "dairy",
    unit: "g",
    kcalPer100: 403,
    proteinPer100: 25,
    packSize: 320,
    packPrice: 6.5,
    packLabel: "320 g bag",
  },
  {
    id: "mozzarella",
    name: "Mozzarella, shredded",
    aisle: "dairy",
    unit: "g",
    kcalPer100: 300,
    proteinPer100: 22,
    packSize: 320,
    packPrice: 6.0,
    packLabel: "320 g bag",
  },
  {
    id: "parmesan",
    name: "Parmesan, grated",
    aisle: "dairy",
    unit: "g",
    kcalPer100: 420,
    proteinPer100: 38,
    packSize: 250,
    packPrice: 7.5,
    packLabel: "250 g tub",
  },
  {
    id: "feta",
    name: "Feta",
    aisle: "dairy",
    unit: "g",
    kcalPer100: 264,
    proteinPer100: 14,
    packSize: 200,
    packPrice: 5.5,
    packLabel: "200 g block",
  },

  // ---------- Produce ----------
  {
    id: "broccoli",
    name: "Broccoli",
    aisle: "produce",
    unit: "g",
    kcalPer100: 34,
    proteinPer100: 2.8,
    packSize: 400,
    packPrice: 2.5,
    packLabel: "head (~400 g)",
    eachGrams: 400,
    eachLabel: "head",
  },
  {
    id: "bell-pepper",
    name: "Bell peppers",
    aisle: "produce",
    unit: "g",
    kcalPer100: 31,
    proteinPer100: 1,
    packSize: 500,
    packPrice: 5.0,
    packLabel: "3-pack",
    eachGrams: 165,
    eachLabel: "pepper",
  },
  {
    id: "onion",
    name: "Yellow onions",
    aisle: "produce",
    unit: "g",
    kcalPer100: 40,
    proteinPer100: 1.1,
    packSize: 1360,
    packPrice: 4.0,
    packLabel: "3 lb bag",
    eachGrams: 170,
    eachLabel: "onion",
  },
  {
    id: "garlic",
    name: "Garlic",
    aisle: "produce",
    unit: "g",
    kcalPer100: 149,
    proteinPer100: 6.4,
    packSize: 180,
    packPrice: 2.5,
    packLabel: "3 bulbs",
    eachGrams: 5,
    eachLabel: "clove",
  },
  {
    id: "carrot",
    name: "Carrots",
    aisle: "produce",
    unit: "g",
    kcalPer100: 41,
    proteinPer100: 0.9,
    packSize: 900,
    packPrice: 2.5,
    packLabel: "2 lb bag",
    eachGrams: 70,
    eachLabel: "carrot",
  },
  {
    id: "spinach",
    name: "Baby spinach",
    aisle: "produce",
    unit: "g",
    kcalPer100: 23,
    proteinPer100: 2.9,
    packSize: 280,
    packPrice: 5.0,
    packLabel: "280 g clamshell",
  },
  {
    id: "cherry-tomato",
    name: "Cherry tomatoes",
    aisle: "produce",
    unit: "g",
    kcalPer100: 18,
    proteinPer100: 0.9,
    packSize: 500,
    packPrice: 4.5,
    packLabel: "500 g punnet",
  },
  {
    id: "cucumber",
    name: "English cucumber",
    aisle: "produce",
    unit: "g",
    kcalPer100: 15,
    proteinPer100: 0.7,
    packSize: 300,
    packPrice: 2.0,
    packLabel: "each",
    eachGrams: 300,
    eachLabel: "cucumber",
  },
  {
    id: "potato",
    name: "Yellow potatoes",
    aisle: "produce",
    unit: "g",
    kcalPer100: 77,
    proteinPer100: 2,
    packSize: 2270,
    packPrice: 5.5,
    packLabel: "5 lb bag",
  },
  {
    id: "sweet-potato",
    name: "Sweet potatoes",
    aisle: "produce",
    unit: "g",
    kcalPer100: 86,
    proteinPer100: 1.6,
    packSize: 1000,
    packPrice: 3.5,
    packLabel: "~1 kg",
  },
  {
    id: "green-beans",
    name: "Green beans",
    aisle: "produce",
    unit: "g",
    kcalPer100: 31,
    proteinPer100: 1.8,
    packSize: 340,
    packPrice: 3.5,
    packLabel: "340 g bag",
  },
  {
    id: "romaine",
    name: "Romaine lettuce",
    aisle: "produce",
    unit: "g",
    kcalPer100: 17,
    proteinPer100: 1.2,
    packSize: 300,
    packPrice: 3.0,
    packLabel: "head",
    eachGrams: 300,
    eachLabel: "head",
  },
  {
    id: "lime",
    name: "Limes",
    aisle: "produce",
    unit: "g",
    kcalPer100: 30,
    proteinPer100: 0.7,
    packSize: 300,
    packPrice: 2.5,
    packLabel: "5-pack",
    eachGrams: 60,
    eachLabel: "lime",
  },
  {
    id: "ginger",
    name: "Fresh ginger",
    aisle: "produce",
    unit: "g",
    kcalPer100: 80,
    proteinPer100: 1.8,
    packSize: 100,
    packPrice: 1.5,
    packLabel: "knob",
  },

  // ---------- Grains ----------
  {
    id: "rice",
    name: "Jasmine rice (dry)",
    aisle: "grains",
    unit: "g",
    kcalPer100: 360,
    proteinPer100: 7,
    packSize: 4000,
    packPrice: 13.0,
    packLabel: "4 kg bag",
    staple: true,
  },
  {
    id: "quinoa",
    name: "Quinoa (dry)",
    aisle: "grains",
    unit: "g",
    kcalPer100: 368,
    proteinPer100: 14,
    packSize: 900,
    packPrice: 9.0,
    packLabel: "900 g bag",
    staple: true,
  },
  {
    id: "pasta",
    name: "Spaghetti / penne",
    aisle: "grains",
    unit: "g",
    kcalPer100: 371,
    proteinPer100: 13,
    packSize: 900,
    packPrice: 2.5,
    packLabel: "900 g box",
  },
  {
    id: "tortilla",
    name: "Flour tortillas",
    aisle: "grains",
    unit: "g",
    kcalPer100: 310,
    proteinPer100: 8,
    packSize: 450,
    packPrice: 4.0,
    packLabel: "10-pack",
    eachGrams: 45,
    eachLabel: "tortilla",
  },

  // ---------- Pantry ----------
  {
    id: "black-beans",
    name: "Black beans, canned",
    aisle: "pantry",
    unit: "g",
    kcalPer100: 132,
    proteinPer100: 8.9,
    packSize: 380,
    packPrice: 1.5,
    packLabel: "540 ml tin",
    eachGrams: 380,
    eachLabel: "tin",
  },
  {
    id: "chickpeas",
    name: "Chickpeas, canned",
    aisle: "pantry",
    unit: "g",
    kcalPer100: 164,
    proteinPer100: 8.9,
    packSize: 380,
    packPrice: 1.6,
    packLabel: "540 ml tin",
    eachGrams: 380,
    eachLabel: "tin",
  },
  {
    id: "canned-tomato",
    name: "Diced tomatoes",
    aisle: "pantry",
    unit: "g",
    kcalPer100: 32,
    proteinPer100: 1.6,
    packSize: 796,
    packPrice: 2.0,
    packLabel: "796 ml tin",
    eachGrams: 796,
    eachLabel: "tin",
  },
  {
    id: "tomato-paste",
    name: "Tomato paste",
    aisle: "pantry",
    unit: "g",
    kcalPer100: 82,
    proteinPer100: 4.3,
    packSize: 156,
    packPrice: 1.5,
    packLabel: "156 ml tin",
  },
  {
    id: "coconut-milk",
    name: "Coconut milk",
    aisle: "pantry",
    unit: "ml",
    kcalPer100: 197,
    proteinPer100: 2,
    packSize: 400,
    packPrice: 2.5,
    packLabel: "400 ml tin",
    eachGrams: 400,
    eachLabel: "tin",
  },
  {
    id: "salsa",
    name: "Salsa",
    aisle: "pantry",
    unit: "g",
    kcalPer100: 36,
    proteinPer100: 1.5,
    packSize: 650,
    packPrice: 4.5,
    packLabel: "650 ml jar",
  },
  {
    id: "curry-paste",
    name: "Curry paste",
    aisle: "pantry",
    unit: "g",
    kcalPer100: 150,
    proteinPer100: 3,
    packSize: 200,
    packPrice: 5.0,
    packLabel: "200 g jar",
    staple: true,
  },
  {
    id: "peanut-butter",
    name: "Peanut butter",
    aisle: "pantry",
    unit: "g",
    kcalPer100: 588,
    proteinPer100: 25,
    packSize: 1000,
    packPrice: 6.5,
    packLabel: "1 kg jar",
    staple: true,
  },
  {
    id: "soy-sauce",
    name: "Soy sauce",
    aisle: "pantry",
    unit: "ml",
    kcalPer100: 53,
    proteinPer100: 8,
    packSize: 500,
    packPrice: 4.0,
    packLabel: "500 ml bottle",
    staple: true,
  },
  {
    id: "honey",
    name: "Honey",
    aisle: "pantry",
    unit: "g",
    kcalPer100: 304,
    proteinPer100: 0.3,
    packSize: 500,
    packPrice: 8.0,
    packLabel: "500 g jar",
    staple: true,
  },
  {
    id: "olive-oil",
    name: "Olive oil",
    aisle: "pantry",
    unit: "ml",
    kcalPer100: 884,
    proteinPer100: 0,
    packSize: 750,
    packPrice: 12.0,
    packLabel: "750 ml bottle",
    staple: true,
  },
  {
    id: "chicken-broth",
    name: "Chicken broth",
    aisle: "pantry",
    unit: "ml",
    kcalPer100: 4,
    proteinPer100: 0.8,
    packSize: 900,
    packPrice: 3.0,
    packLabel: "900 ml carton",
  },
  {
    id: "spices",
    name: "Spices & seasoning",
    aisle: "pantry",
    unit: "g",
    kcalPer100: 250,
    proteinPer100: 10,
    packSize: 400,
    packPrice: 14.0,
    packLabel: "restock jars",
    staple: true,
  },
];

export const BY_ID: Record<string, Ingredient> = Object.fromEntries(
  INGREDIENTS.map((i) => [i.id, i]),
);

export function unitPrice(ing: Ingredient): number {
  return ing.packPrice / ing.packSize;
}

/** Phrase an amount the way it reads on a shopping list. */
export function describeQty(ing: Ingredient, qty: number): string {
  if (ing.eachGrams) {
    const count = qty / ing.eachGrams;
    const rounded = count < 1 ? Math.round(count * 2) / 2 : Math.round(count);
    if (rounded >= 0.5) {
      const plural = rounded === 1 ? ing.eachLabel : `${ing.eachLabel}s`;
      return `${rounded} ${plural}`;
    }
  }
  if (qty >= 1000) return `${(qty / 1000).toFixed(qty % 1000 === 0 ? 0 : 1)} ${ing.unit === "ml" ? "L" : "kg"}`;
  return `${Math.round(qty)} ${ing.unit}`;
}
