import type { Meal } from "./types";

/**
 * Quantities are per serving. Every meal is portioned to land near 1000 kcal
 * and 55 g+ of protein, so a lunch plus a dinner is roughly a 2000 kcal,
 * high-protein day before breakfast and snacks.
 *
 * The pool deliberately leans on a narrow set of core ingredients (chicken,
 * beef, turkey, rice, peppers, onion, garlic, broccoli) so the planner can pick
 * a varied week that still resolves to one tight shop.
 */
export const MEALS: Meal[] = [
  // ============================ LUNCHES ============================
  {
    id: "burrito-bowl",
    name: "Chicken Burrito Bowl",
    slot: "lunch",
    blurb: "Charred thigh, black beans, rice, salsa. The workhorse of the rotation.",
    ingredients: [
      { id: "chicken-thigh", qty: 180 },
      { id: "rice", qty: 75 },
      { id: "black-beans", qty: 100 },
      { id: "bell-pepper", qty: 80 },
      { id: "onion", qty: 40 },
      { id: "cheddar", qty: 30 },
      { id: "salsa", qty: 60 },
      { id: "lime", qty: 15 },
      { id: "olive-oil", qty: 8 },
      { id: "spices", qty: 4 },
    ],
    prep: [
      { station: "prep", minutes: 6, text: "Slice peppers and onion. Toss thighs with oil, cumin, paprika, chilli." },
      { station: "stovetop", minutes: 14, text: "Sear thighs hard in a dry-hot pan, 6 min a side. Rest, then chop into chunks." },
      { station: "stovetop", minutes: 4, text: "Blister the peppers and onion in the same pan. Fold in drained black beans to warm through." },
      { station: "portion", minutes: 5, text: "Rice on the bottom, chicken and beans on top, peppers alongside. Salsa and cheese in a separate lidded pot." },
    ],
    assemble: [
      "Microwave the bowl 2.5 min, stir, another 1 min.",
      "Spoon over salsa, scatter cheese, squeeze the lime wedge.",
    ],
    assembleMinutes: 5,
    keepsDays: 4,
    freezes: true,
  },
  {
    id: "greek-quinoa",
    name: "Greek Chicken Quinoa Bowl",
    slot: "lunch",
    blurb: "Eaten cold, so there is nothing to reheat. Highest protein in the pool.",
    ingredients: [
      { id: "chicken-breast", qty: 200 },
      { id: "quinoa", qty: 90 },
      { id: "cucumber", qty: 80 },
      { id: "cherry-tomato", qty: 80 },
      { id: "feta", qty: 35 },
      { id: "greek-yogurt", qty: 80 },
      { id: "garlic", qty: 5 },
      { id: "olive-oil", qty: 12 },
      { id: "lime", qty: 15 },
      { id: "spices", qty: 3 },
    ],
    prep: [
      { station: "prep", minutes: 5, text: "Butterfly the breasts. Marinate in oil, lime, oregano, garlic." },
      { station: "oven", minutes: 22, text: "Roast at 425°F for 20 min. Rest 5 min, then slice." },
      { station: "prep", minutes: 6, text: "Dice cucumber and halve tomatoes. Stir grated garlic and lime into the yogurt for tzatziki." },
      { station: "portion", minutes: 5, text: "Quinoa down first, chicken and veg on top. Feta and tzatziki in separate pots — they turn the bowl watery if packed together." },
    ],
    assemble: [
      "Eat straight from the fridge, no microwave.",
      "Crumble the feta over, spoon the tzatziki on, toss.",
    ],
    assembleMinutes: 3,
    keepsDays: 4,
    freezes: false,
  },
  {
    id: "teriyaki-beef",
    name: "Teriyaki Beef & Rice",
    slot: "lunch",
    blurb: "Sticky soy-honey beef over rice. Reheats better than almost anything.",
    ingredients: [
      { id: "ground-beef", qty: 180 },
      { id: "rice", qty: 90 },
      { id: "broccoli", qty: 120 },
      { id: "carrot", qty: 60 },
      { id: "soy-sauce", qty: 20 },
      { id: "honey", qty: 12 },
      { id: "garlic", qty: 5 },
      { id: "ginger", qty: 5 },
      { id: "olive-oil", qty: 8 },
    ],
    prep: [
      { station: "prep", minutes: 5, text: "Grate garlic and ginger. Julienne carrots, cut broccoli into small florets." },
      { station: "stovetop", minutes: 12, text: "Brown the beef hard, drain the fat, add garlic and ginger, then soy and honey. Reduce until it glazes." },
      { station: "stovetop", minutes: 4, text: "Blanch broccoli and carrot 90 seconds, then straight into ice water so they stay crisp all week." },
      { station: "portion", minutes: 4, text: "Rice, beef, veg. Sauce clings to the beef, so it will not go soggy." },
    ],
    assemble: ["Microwave 3 min covered, stir halfway."],
    assembleMinutes: 4,
    keepsDays: 4,
    freezes: true,
  },
  {
    id: "chicken-chickpea-curry",
    name: "Chicken & Chickpea Curry",
    slot: "lunch",
    blurb: "Genuinely better on day three. Freezes hard, thaws clean.",
    ingredients: [
      { id: "chicken-thigh", qty: 170 },
      { id: "chickpeas", qty: 120 },
      { id: "coconut-milk", qty: 80 },
      { id: "curry-paste", qty: 25 },
      { id: "onion", qty: 60 },
      { id: "garlic", qty: 6 },
      { id: "spinach", qty: 50 },
      { id: "rice", qty: 65 },
      { id: "olive-oil", qty: 6 },
    ],
    prep: [
      { station: "prep", minutes: 4, text: "Dice onion, mince garlic, cube the thighs." },
      { station: "stovetop", minutes: 22, text: "Soften onion, bloom the curry paste 60 seconds, add chicken, chickpeas and coconut milk. Simmer 15 min." },
      { station: "stovetop", minutes: 2, text: "Kill the heat, stir the spinach through so it wilts in residual heat rather than going grey." },
      { station: "portion", minutes: 4, text: "Curry and rice in the same tub is fine here — the rice soaking up sauce is the point." },
    ],
    assemble: ["Microwave 3.5 min covered, stir halfway."],
    assembleMinutes: 4,
    keepsDays: 5,
    freezes: true,
  },
  {
    id: "turkey-chili",
    name: "Turkey Chili",
    slot: "lunch",
    blurb: "One pot, cheap, and the leftovers keep the longest of anything here.",
    ingredients: [
      { id: "ground-turkey", qty: 180 },
      { id: "black-beans", qty: 130 },
      { id: "canned-tomato", qty: 200 },
      { id: "bell-pepper", qty: 90 },
      { id: "onion", qty: 60 },
      { id: "garlic", qty: 6 },
      { id: "cheddar", qty: 30 },
      { id: "rice", qty: 60 },
      { id: "spices", qty: 6 },
      { id: "olive-oil", qty: 8 },
    ],
    prep: [
      { station: "prep", minutes: 5, text: "Dice onion and peppers, mince garlic." },
      { station: "stovetop", minutes: 30, text: "Brown turkey, add aromatics, then chilli powder, cumin and smoked paprika. Tomatoes and beans in, simmer 20 min uncovered until it thickens." },
      { station: "portion", minutes: 4, text: "Chili over rice. Cheese in a separate pot — it goes rubbery if microwaved twice." },
    ],
    assemble: ["Microwave 3 min covered.", "Scatter the cheese on after heating, not before."],
    assembleMinutes: 4,
    keepsDays: 5,
    freezes: true,
  },
  {
    id: "salmon-sweet-potato",
    name: "Salmon & Sweet Potato Bowl",
    slot: "lunch",
    blurb: "The one splurge. Eat it early in the week — fish does not hold like chicken.",
    ingredients: [
      { id: "salmon", qty: 200 },
      { id: "sweet-potato", qty: 300 },
      { id: "broccoli", qty: 130 },
      { id: "quinoa", qty: 40 },
      { id: "greek-yogurt", qty: 60 },
      { id: "olive-oil", qty: 12 },
      { id: "lime", qty: 15 },
      { id: "garlic", qty: 5 },
      { id: "spices", qty: 3 },
    ],
    prep: [
      { station: "prep", minutes: 5, text: "Cube sweet potato, cut broccoli into florets. Toss both in oil, salt, paprika." },
      { station: "oven", minutes: 28, text: "Roast sweet potato at 425°F for 25 min. Broccoli joins for the last 12 min only." },
      { station: "oven", minutes: 12, text: "Salmon on a separate tray, 10-12 min at 425°F. Pull it slightly under — it finishes cooking when you reheat." },
      { station: "portion", minutes: 4, text: "Quinoa, salmon, veg. Yogurt whisked with lime and garlic goes in its own pot." },
    ],
    assemble: [
      "Microwave 2 min only — salmon overcooks fast.",
      "Spoon over the lime-garlic yogurt.",
    ],
    assembleMinutes: 4,
    keepsDays: 3,
    freezes: false,
  },
  {
    id: "beef-broccoli",
    name: "Beef & Broccoli Stir Fry",
    slot: "lunch",
    blurb: "Fifteen minutes on Sunday and it tastes the same on Friday.",
    ingredients: [
      { id: "ground-beef", qty: 170 },
      { id: "broccoli", qty: 180 },
      { id: "carrot", qty: 70 },
      { id: "rice", qty: 95 },
      { id: "soy-sauce", qty: 20 },
      { id: "garlic", qty: 6 },
      { id: "ginger", qty: 6 },
      { id: "olive-oil", qty: 8 },
    ],
    prep: [
      { station: "prep", minutes: 5, text: "Broccoli into small florets, carrots on the bias, garlic and ginger grated." },
      { station: "stovetop", minutes: 12, text: "Beef browned and drained, aromatics in, soy to deglaze. Broccoli and carrot in for the last 3 min only — they should squeak." },
      { station: "portion", minutes: 4, text: "Rice down, stir fry on top." },
    ],
    assemble: ["Microwave 3 min covered, stir halfway."],
    assembleMinutes: 4,
    keepsDays: 4,
    freezes: true,
  },
  {
    id: "tuna-pasta",
    name: "Tuna Pasta Salad",
    slot: "lunch",
    blurb: "No cooking on the day and no microwave queue. Cheapest meal in the pool.",
    ingredients: [
      { id: "tuna-can", qty: 170 },
      { id: "pasta", qty: 130 },
      { id: "greek-yogurt", qty: 90 },
      { id: "cherry-tomato", qty: 80 },
      { id: "cucumber", qty: 70 },
      { id: "feta", qty: 25 },
      { id: "onion", qty: 30 },
      { id: "olive-oil", qty: 10 },
      { id: "spices", qty: 3 },
    ],
    prep: [
      { station: "stovetop", minutes: 12, text: "Boil pasta one minute past al dente — it firms up cold. Rinse under cold water and toss in the oil so it does not clag." },
      { station: "prep", minutes: 6, text: "Halve tomatoes, dice cucumber, finely slice red onion. Flake the tuna into the yogurt with black pepper and dill." },
      { station: "portion", minutes: 4, text: "Everything mixed together and packed. This one genuinely improves overnight." },
    ],
    assemble: ["Eat cold, straight from the tub.", "Crumble feta over if you kept it separate."],
    assembleMinutes: 2,
    keepsDays: 3,
    freezes: false,
  },
  {
    id: "turkey-egg-hash",
    name: "Turkey & Egg Hash",
    slot: "lunch",
    blurb: "Breakfast food at noon. Crisps back up in a pan if you have a spare minute.",
    ingredients: [
      { id: "eggs", qty: 200 },
      { id: "ground-turkey", qty: 100 },
      { id: "potato", qty: 300 },
      { id: "bell-pepper", qty: 80 },
      { id: "onion", qty: 50 },
      { id: "cheddar", qty: 40 },
      { id: "spinach", qty: 50 },
      { id: "olive-oil", qty: 12 },
      { id: "spices", qty: 3 },
    ],
    prep: [
      { station: "prep", minutes: 6, text: "Dice potatoes small — 1 cm, or they will not cook through. Dice pepper and onion." },
      { station: "oven", minutes: 30, text: "Potatoes tossed in oil and paprika, roasted at 425°F for 25-30 min until the edges go hard." },
      { station: "stovetop", minutes: 10, text: "Brown the turkey with the pepper and onion. Wilt spinach in at the end. Fold through the roast potatoes." },
      { station: "stovetop", minutes: 6, text: "Soft-boil the eggs 7 min, ice bath, then leave them in their shells until the morning you eat them." },
      { station: "portion", minutes: 4, text: "Hash in the tub, eggs and cheese kept separate." },
    ],
    assemble: [
      "Microwave the hash 2.5 min.",
      "Peel and halve the eggs, sit them on top, scatter the cheese over the heat.",
    ],
    assembleMinutes: 5,
    keepsDays: 4,
    freezes: false,
  },
  {
    id: "peanut-chicken",
    name: "Peanut Chicken Rice Bowl",
    slot: "lunch",
    blurb: "Satay-ish, high protein, and the sauce keeps the chicken from drying out.",
    ingredients: [
      { id: "chicken-breast", qty: 190 },
      { id: "rice", qty: 95 },
      { id: "peanut-butter", qty: 30 },
      { id: "soy-sauce", qty: 15 },
      { id: "carrot", qty: 70 },
      { id: "broccoli", qty: 120 },
      { id: "garlic", qty: 5 },
      { id: "ginger", qty: 5 },
      { id: "lime", qty: 15 },
      { id: "honey", qty: 8 },
    ],
    prep: [
      { station: "prep", minutes: 5, text: "Cube the chicken. Whisk peanut butter, soy, honey, lime, grated garlic and ginger with a splash of hot water into a pourable sauce." },
      { station: "stovetop", minutes: 12, text: "Sear the chicken in batches so it browns instead of steaming. Toss in half the sauce off the heat." },
      { station: "stovetop", minutes: 4, text: "Blanch broccoli and carrot 90 seconds, then ice water." },
      { station: "portion", minutes: 4, text: "Rice, chicken, veg. Remaining sauce in a separate pot." },
    ],
    assemble: [
      "Microwave 3 min covered.",
      "Pour the reserved peanut sauce over and toss.",
    ],
    assembleMinutes: 4,
    keepsDays: 4,
    freezes: true,
  },

  // ============================ DINNERS ============================
  {
    id: "fajita-tray",
    name: "Chicken Fajita Tray Bake",
    slot: "dinner",
    blurb: "One tray, one wash-up. Peppers and onion do all the work.",
    ingredients: [
      { id: "chicken-breast", qty: 200 },
      { id: "bell-pepper", qty: 130 },
      { id: "onion", qty: 70 },
      { id: "tortilla", qty: 90 },
      { id: "cheddar", qty: 35 },
      { id: "salsa", qty: 60 },
      { id: "olive-oil", qty: 12 },
      { id: "lime", qty: 15 },
      { id: "spices", qty: 5 },
    ],
    prep: [
      { station: "prep", minutes: 6, text: "Slice chicken, peppers and onion into strips. Toss everything with oil, cumin, paprika, chilli and lime." },
      { station: "oven", minutes: 25, text: "Spread over one tray — crowd it and it steams. 425°F for 22 min, until the pepper edges char." },
      { station: "portion", minutes: 4, text: "Filling in tubs. Tortillas stay in their bag, cheese and salsa separate." },
    ],
    assemble: [
      "Microwave the filling 3 min.",
      "Warm the tortillas 20 seconds in the same microwave.",
      "Build, add cheese and salsa, squeeze the lime.",
    ],
    assembleMinutes: 6,
    keepsDays: 4,
    freezes: true,
  },
  {
    id: "bolognese",
    name: "Spaghetti Bolognese",
    slot: "dinner",
    blurb: "Sauce made Sunday, pasta boiled fresh in the 9 minutes it takes to reheat.",
    ingredients: [
      { id: "ground-beef", qty: 170 },
      { id: "pasta", qty: 95 },
      { id: "canned-tomato", qty: 180 },
      { id: "tomato-paste", qty: 25 },
      { id: "onion", qty: 60 },
      { id: "garlic", qty: 6 },
      { id: "carrot", qty: 60 },
      { id: "parmesan", qty: 20 },
      { id: "olive-oil", qty: 10 },
      { id: "spices", qty: 4 },
    ],
    prep: [
      { station: "prep", minutes: 5, text: "Finely dice onion, carrot and garlic — small enough that they melt into the sauce." },
      { station: "stovetop", minutes: 35, text: "Soften the veg 8 min, brown the beef, fry the tomato paste 2 min until it darkens, then tomatoes and oregano. Simmer 20 min minimum." },
      { station: "portion", minutes: 3, text: "Sauce only in the tubs. Do not pre-cook the pasta — it turns to paste by Thursday." },
    ],
    assemble: [
      "Boil the pasta (9 min) and microwave the sauce (3 min) at the same time.",
      "Toss together with a splash of pasta water, grate the parmesan over.",
    ],
    assembleMinutes: 10,
    keepsDays: 5,
    freezes: true,
  },
  {
    id: "honey-garlic-chicken",
    name: "Honey Garlic Chicken Thighs",
    slot: "dinner",
    blurb: "Sticky, cheap, and the glaze keeps the thighs juicy for days.",
    ingredients: [
      { id: "chicken-thigh", qty: 200 },
      { id: "rice", qty: 85 },
      { id: "broccoli", qty: 150 },
      { id: "honey", qty: 20 },
      { id: "garlic", qty: 8 },
      { id: "soy-sauce", qty: 20 },
      { id: "olive-oil", qty: 8 },
      { id: "spices", qty: 3 },
    ],
    prep: [
      { station: "prep", minutes: 4, text: "Mince the garlic. Whisk honey, soy and garlic together." },
      { station: "stovetop", minutes: 18, text: "Sear thighs 6 min a side, pour the glaze in, reduce 3 min until it coats the back of a spoon." },
      { station: "stovetop", minutes: 4, text: "Blanch broccoli 90 seconds, ice water." },
      { station: "portion", minutes: 4, text: "Rice, thighs with the glaze spooned over, broccoli alongside." },
    ],
    assemble: ["Microwave 3 min covered, stir the rice halfway."],
    assembleMinutes: 4,
    keepsDays: 4,
    freezes: true,
  },
  {
    id: "salmon-potato",
    name: "Salmon, Roast Potato & Green Beans",
    slot: "dinner",
    blurb: "The nice-dinner slot. Put it on a Monday while the fish is fresh.",
    ingredients: [
      { id: "salmon", qty: 220 },
      { id: "potato", qty: 320 },
      { id: "green-beans", qty: 150 },
      { id: "greek-yogurt", qty: 60 },
      { id: "garlic", qty: 8 },
      { id: "olive-oil", qty: 18 },
      { id: "lime", qty: 15 },
      { id: "spices", qty: 3 },
    ],
    prep: [
      { station: "prep", minutes: 5, text: "Halve the potatoes, top and tail the beans. Whisk yogurt with lime, garlic and dill." },
      { station: "oven", minutes: 35, text: "Potatoes cut-side down at 425°F for 30 min — do not turn them until the crust forms." },
      { station: "portion", minutes: 3, text: "Potatoes in tubs. Salmon stays raw in the fridge, beans stay raw in the bag. Sauce in a pot." },
    ],
    assemble: [
      "Pan-sear the salmon from raw, 4 min skin down, 2 min over.",
      "Beans in the microwave 3 min, potatoes reheat alongside.",
      "Plate and spoon the lime-garlic yogurt over.",
    ],
    assembleMinutes: 9,
    keepsDays: 3,
    freezes: false,
  },
  {
    id: "beef-tacos",
    name: "Beef Tacos",
    slot: "dinner",
    blurb: "Filling made ahead, everything else is assembly. Fastest dinner here.",
    ingredients: [
      { id: "ground-beef", qty: 170 },
      { id: "tortilla", qty: 90 },
      { id: "black-beans", qty: 90 },
      { id: "cheddar", qty: 35 },
      { id: "romaine", qty: 50 },
      { id: "salsa", qty: 60 },
      { id: "onion", qty: 40 },
      { id: "lime", qty: 15 },
      { id: "spices", qty: 5 },
    ],
    prep: [
      { station: "prep", minutes: 4, text: "Dice the onion, shred the romaine and keep it in a bag with a dry paper towel." },
      { station: "stovetop", minutes: 14, text: "Brown the beef, drain, add onion and taco spices, then the beans and a splash of water. Cook down 5 min." },
      { station: "portion", minutes: 3, text: "Filling in tubs. Lettuce, cheese, salsa and tortillas all stay separate." },
    ],
    assemble: [
      "Microwave the filling 2.5 min.",
      "Tortillas 20 seconds.",
      "Build: filling, lettuce, cheese, salsa, lime.",
    ],
    assembleMinutes: 5,
    keepsDays: 4,
    freezes: true,
  },
  {
    id: "butter-chicken",
    name: "Butter Chicken",
    slot: "dinner",
    blurb: "Tastes like a takeaway on day four. Best reheater in the whole rotation.",
    ingredients: [
      { id: "chicken-thigh", qty: 190 },
      { id: "canned-tomato", qty: 180 },
      { id: "coconut-milk", qty: 70 },
      { id: "curry-paste", qty: 25 },
      { id: "onion", qty: 60 },
      { id: "garlic", qty: 6 },
      { id: "greek-yogurt", qty: 50 },
      { id: "rice", qty: 80 },
      { id: "olive-oil", qty: 8 },
    ],
    prep: [
      { station: "prep", minutes: 6, text: "Cube the thighs and marinate in the yogurt with half the curry paste. Twenty minutes minimum, longer is better." },
      { station: "stovetop", minutes: 28, text: "Sear the marinated chicken and set aside. Soften onion and garlic, bloom the rest of the paste, add tomatoes and blitz smooth. Coconut milk in, chicken back, simmer 12 min." },
      { station: "portion", minutes: 4, text: "Curry and rice together — the rice should soak up sauce." },
    ],
    assemble: ["Microwave 3.5 min covered, stir halfway."],
    assembleMinutes: 4,
    keepsDays: 5,
    freezes: true,
  },
  {
    id: "shepherds-pie",
    name: "Shepherd's Pie",
    slot: "dinner",
    blurb: "Assembled Sunday, baked whenever. Portion it into individual tubs.",
    ingredients: [
      { id: "ground-beef", qty: 160 },
      { id: "potato", qty: 300 },
      { id: "carrot", qty: 80 },
      { id: "onion", qty: 60 },
      { id: "tomato-paste", qty: 25 },
      { id: "cheddar", qty: 35 },
      { id: "chicken-broth", qty: 100 },
      { id: "olive-oil", qty: 10 },
      { id: "spices", qty: 4 },
    ],
    prep: [
      { station: "stovetop", minutes: 22, text: "Boil the potatoes 18 min, mash with a splash of broth and plenty of pepper." },
      { station: "stovetop", minutes: 20, text: "Soften onion and carrot, brown the beef, fry the tomato paste, add broth and thyme. Simmer until it thickens — a loose filling makes a soggy pie." },
      { station: "portion", minutes: 6, text: "Layer filling then mash into individual oven-safe tubs. Cheese on top. Do not bake now." },
    ],
    assemble: [
      "Oven at 400°F: 20 min from cold, and it comes out with a proper crust.",
      "In a hurry: microwave 4 min, then 3 min under the broiler for the top.",
    ],
    assembleMinutes: 5,
    keepsDays: 4,
    freezes: true,
  },
  {
    id: "stuffed-peppers",
    name: "Stuffed Peppers",
    slot: "dinner",
    blurb: "Uses up the pepper multipack. Stuffed Sunday, baked on the night.",
    ingredients: [
      { id: "ground-turkey", qty: 180 },
      { id: "bell-pepper", qty: 330 },
      { id: "rice", qty: 70 },
      { id: "canned-tomato", qty: 150 },
      { id: "onion", qty: 50 },
      { id: "garlic", qty: 5 },
      { id: "mozzarella", qty: 45 },
      { id: "olive-oil", qty: 10 },
      { id: "spices", qty: 4 },
    ],
    prep: [
      { station: "prep", minutes: 6, text: "Halve the peppers lengthways and pull the seeds. Dice onion, mince garlic." },
      { station: "stovetop", minutes: 16, text: "Brown turkey with onion, garlic and oregano. Tomatoes in, reduce 8 min, then fold the cooked rice through." },
      { station: "portion", minutes: 6, text: "Stuff the pepper halves and pack them raw. Mozzarella separate — added now it just burns." },
    ],
    assemble: [
      "Oven at 400°F for 18 min.",
      "Mozzarella on for the last 5 min.",
    ],
    assembleMinutes: 4,
    keepsDays: 4,
    freezes: true,
  },
  {
    id: "chicken-parm",
    name: "Chicken Parm & Pasta",
    slot: "dinner",
    blurb: "93 g of protein, the highest here. Sauce and chicken prep, pasta fresh.",
    ingredients: [
      { id: "chicken-breast", qty: 190 },
      { id: "pasta", qty: 100 },
      { id: "canned-tomato", qty: 180 },
      { id: "mozzarella", qty: 45 },
      { id: "parmesan", qty: 20 },
      { id: "garlic", qty: 6 },
      { id: "olive-oil", qty: 10 },
      { id: "spices", qty: 4 },
    ],
    prep: [
      { station: "prep", minutes: 5, text: "Butterfly and flatten the breasts to an even thickness so they cook through evenly." },
      { station: "stovetop", minutes: 20, text: "Sear the chicken 4 min a side. In the same pan, garlic then tomatoes and basil, simmer 12 min." },
      { station: "portion", minutes: 4, text: "Chicken sitting in the sauce — it keeps it from drying out. Cheese separate." },
    ],
    assemble: [
      "Boil the pasta (9 min) while the chicken and sauce microwave 3 min.",
      "Cheese over the chicken, 3 min under the broiler until it blisters.",
    ],
    assembleMinutes: 10,
    keepsDays: 4,
    freezes: true,
  },
  {
    id: "pork-sweet-mash",
    name: "Pork Chops & Sweet Potato Mash",
    slot: "dinner",
    blurb: "Mash made ahead, chops seared fresh in 8 minutes. Cheapest protein per gram.",
    ingredients: [
      { id: "pork-loin", qty: 200 },
      { id: "sweet-potato", qty: 300 },
      { id: "green-beans", qty: 150 },
      { id: "greek-yogurt", qty: 40 },
      { id: "garlic", qty: 6 },
      { id: "olive-oil", qty: 12 },
      { id: "spices", qty: 3 },
    ],
    prep: [
      { station: "stovetop", minutes: 22, text: "Boil sweet potato 15 min, mash with the yogurt, garlic and a big pinch of salt." },
      { station: "prep", minutes: 4, text: "Top and tail the beans. Rub the chops with oil, salt, pepper and fennel seed, and leave them raw in the fridge." },
      { station: "portion", minutes: 3, text: "Mash in tubs. Chops and beans stay raw — pork reheated from cooked goes to leather." },
    ],
    assemble: [
      "Sear the chops from raw, 4 min a side, rest 2 min.",
      "Mash microwaves 2.5 min, beans 3 min alongside.",
    ],
    assembleMinutes: 9,
    keepsDays: 4,
    freezes: false,
  },
];

export const MEAL_BY_ID: Record<string, Meal> = Object.fromEntries(
  MEALS.map((m) => [m.id, m]),
);

export const LUNCH_POOL = MEALS.filter((m) => m.slot === "lunch");
export const DINNER_POOL = MEALS.filter((m) => m.slot === "dinner");
